version: "3.7"

services:

  composer:
    image: composer
    container_name: composer
    volumes:
      - .:/app

  redis:
    image: redis:5.0.3-alpine
    container_name: redis
    ports:
      - "6379:6379"

  php:
    image: php:7.4.5-fpm-alpine
    container_name: php
    volumes:
     - .:/usr/share/nginx
     - ./public:/usr/share/nginx/html
    ports:
     - "9000:9000"

  nginx:
    image: nginx:1.14.2-alpine
    container_name: nginx
    volumes:
     - .:/usr/share/nginx
     - ./public:/usr/share/nginx/html
     - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
     - "8080:80"
